import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    card: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
    },
    courseHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    label: {
        fontSize: 15,
        fontWeight: '800',
        color: '#0A2647',
        marginBottom: 8,
    },
    input: {
        borderWidth: 1.5,
        borderColor: '#dee2e6',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 15,
        color: '#212529',
        backgroundColor: '#f8f9fa',
        width: '100%',
    },
    removeBtn: {
        padding: 4,
    },
    parSumBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
        marginBottom: 12,
    },
    parSumOk: {
        backgroundColor: '#E8F8F0',
    },
    parSumWarn: {
        backgroundColor: '#FFF0F0',
    },
    parSumText: {
        fontSize: 11,
        fontWeight: '700',
    },
    parSumTextOk: {
        color: '#2ECC71',
    },
    parSumTextWarn: {
        color: '#FF6B6B',
    },
    teeToggleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
        flexWrap: 'wrap',
    },
    teeToggleLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#6c757d',
    },
    teeToggleBtn: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#dee2e6',
        backgroundColor: '#f8f9fa',
    },
    teeToggleBtnText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#6c757d',
    },
    parGrid: {
        marginTop: 4,
        overflow: 'hidden',
    },
    gridHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 6,
        marginBottom: 8,
        gap: 8,
    },
    gridHeaderText: {
        fontSize: 10,
        color: '#adb5bd',
        fontWeight: '800',
        textAlign: 'center',
    },
    gridHeaderTee: {
        flex: 1,
    },
    holeInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
        gap: 8,
    },
    holeNumberBadge: {
        width: 30,
        height: 30,
        borderRadius: 8,
        backgroundColor: '#F1F3F5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    holeNumberText: {
        fontSize: 12,
        fontWeight: '800',
        color: '#495057',
    },
    parInputSmall: {
        width: 46,
        height: 38,
        borderWidth: 1.5,
        borderColor: '#E9ECEF',
        borderRadius: 8,
        textAlign: 'center',
        fontSize: 14,
        fontWeight: '700',
        color: '#212529',
        backgroundColor: '#fff',
    },
    distanceInput: {
        flex: 1,
        height: 38,
        borderWidth: 1.5,
        borderColor: '#E9ECEF',
        borderRadius: 8,
        paddingHorizontal: 10,
        fontSize: 13,
        fontWeight: '600',
        color: '#212529',
        backgroundColor: '#fff',
    },
    issuesCard: {
        backgroundColor: '#FFF0F0',
        borderRadius: 14,
        padding: 14,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#FF6B6B20',
    },
    issuesTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: '#FF6B6B',
        marginBottom: 6,
    },
    issueItem: {
        fontSize: 12,
        color: '#E03131',
        marginBottom: 2,
        fontWeight: '500',
    },
});
