import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    centered: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
    },
    scrollContent: {
        padding: 20,
    },
    adminBadge: {
        alignSelf: 'flex-start',
        backgroundColor: '#FF6B6B',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 8,
        marginBottom: 16,
    },
    adminBadgeText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1.2,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06)',
    },
    label: {
        fontSize: 15,
        fontWeight: '800',
        color: '#0A2647',
        marginBottom: 8,
    },
    input: {
        borderWidth: 1.5,
        borderColor: '#dee2e6',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 15,
        color: '#212529',
        backgroundColor: '#f8f9fa',
        width: '100%',
    },
    inputHelp: {
        fontSize: 11,
        color: '#6E85B7',
        marginTop: 6,
        fontWeight: '600',
    },
    loadBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        backgroundColor: '#E7F1FF',
        borderRadius: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#007AFF20',
    },
    loadBtnText: {
        color: '#007AFF',
        fontSize: 14,
        fontWeight: '800',
    },
    addCourseBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#0A2647',
        borderStyle: 'dashed',
        marginBottom: 16,
    },
    addCourseBtnText: {
        color: '#0A2647',
        fontSize: 15,
        fontWeight: '700',
    },
    saveBtn: {
        flexDirection: 'row',
        backgroundColor: '#0A2647',
        paddingVertical: 18,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    saveBtnText: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '900',
    },
    verificationRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    verifyStatusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        borderWidth: 1,
    },
    verifyBadgeValid: {
        backgroundColor: '#E7F1FF',
        borderColor: '#007AFF',
    },
    verifyBadgeInvalid: {
        backgroundColor: '#f1f3f5',
        borderColor: '#dee2e6',
    },
    verifyStatusText: {
        fontSize: 12,
        fontWeight: '800',
    },
    verifyTextValid: {
        color: '#007AFF',
    },
    verifyTextInvalid: {
        color: '#adb5bd',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(10, 38, 71, 0.4)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        maxHeight: '80%',
        boxShadow: '0 -4px 20px rgba(0,0,0,0.1)',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: '#0A2647',
    },
    searchBarContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 16,
        paddingHorizontal: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E9ECEF',
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#212529',
        paddingVertical: 12,
        fontWeight: '600',
    },
    clubListScroll: {
        marginBottom: 20,
    },
    clubListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 18,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f3f5',
    },
    clubListItemName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#212529',
    },
    clubListItemCourse: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    courseCountText: {
        fontSize: 13,
        color: '#adb5bd',
        fontWeight: '600',
    },
    emptyListText: {
        textAlign: 'center',
        color: '#adb5bd',
        paddingVertical: 40,
        fontWeight: '600',
    },
    emptyContainer: {
        paddingVertical: 60,
        alignItems: 'center',
    },
    listStats: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        marginBottom: 12,
    },
    listStatsText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#6E85B7',
        textAlign: 'center',
    },
    verifiedBadgeMini: {
        backgroundColor: '#007AFF',
        width: 16,
        height: 16,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    verifiedBadgeTextMini: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '900',
    },
    blockedTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#0A2647',
        marginBottom: 8,
    },
    blockedSub: {
        fontSize: 14,
        color: '#adb5bd',
    },
});
