import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  courseSelectContainer: { flex: 1, padding: 30, justifyContent: 'center', backgroundColor: '#F8F9FA' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 16, color: '#6E85B7', fontWeight: '600' },
  headerRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  title: { fontSize: 28, fontWeight: '900', color: '#0A2647', marginBottom: 16, textAlign: 'center' },
  searchWrapper: {
    marginBottom: 16,
  },
  searchInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#333',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1.5,
    borderColor: '#E9ECEF',
  },
  searchResultCount: {
    marginTop: 8,
    fontSize: 12,
    color: '#6E85B7',
    fontWeight: '600',
    textAlign: 'right',
  },
  selectItem: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  selectText: { fontSize: 18, fontWeight: '700', color: '#333' },
  selectSubText: { fontSize: 12, color: '#adb5bd', marginTop: 4 },
  // 코스명 + 방향 뱃지 행 레이아웃
  courseNameRow: { flexDirection: 'row', alignItems: 'center' },
  directionBadge: {
    backgroundColor: '#4A6FA5',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 8,
  },
  directionBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  emptyState: { alignItems: 'center', paddingVertical: 40, gap: 8 },
  emptyStateText: { fontSize: 15, fontWeight: '700', color: '#495057' },
  emptyStateSubText: { fontSize: 13, color: '#adb5bd', textAlign: 'center' },
  backStepBtn: { marginTop: 10, alignSelf: 'center', padding: 10 },
  backStepBtnText: { color: '#6E85B7', fontWeight: '700', textDecorationLine: 'underline' },
  selectedClubLabel: { fontSize: 14, fontWeight: '700', color: '#6E85B7', textAlign: 'center', marginTop: -8, marginBottom: 16 },
  // 구장 요청 스타일
  requestButtonInline: {
    marginTop: 12,
    backgroundColor: '#0A2647',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  requestButtonTextInline: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  bottomRequestBtn: {
    paddingVertical: 15,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E9ECEF',
    marginTop: 10,
  },
  bottomRequestBtnText: {
    color: '#6E85B7',
    fontSize: 14,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  // 모달 스타일
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 38, 71, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: '#fff',
    width: '100%',
    maxWidth: 400,
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    shadowColor: '#0A2647',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0A2647',
    marginBottom: 10,
    letterSpacing: -0.5,
  },
  modalDesc: {
    fontSize: 15,
    color: '#6E85B7',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
    fontWeight: '500',
  },
  modalInput: {
    width: '100%',
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 18,
    fontSize: 16,
    color: '#333',
    borderWidth: 1.5,
    borderColor: '#E9ECEF',
    marginBottom: 24,
    fontWeight: '600',
  },
  modalButtons: {
    flexDirection: 'row',
    width: '100%',
    gap: 12,
  },
  modalBtn: {
    flex: 1,
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelBtn: {
    backgroundColor: '#F1F3F5',
  },
  submitBtn: {
    backgroundColor: '#0A2647',
    shadowColor: '#0A2647',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  cancelBtnText: {
    color: '#495057',
    fontWeight: '700',
    fontSize: 16,
  },
  submitBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
});
