import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)', // 페이드 아웃 시 잔상 최소화 및 시각적 깊이 확보
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16, // Section 11.4: WINDOW_WIDTH - 32 규격 준수
  },
  scoreCardContainer: {
    width: '100%',
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 50,
    elevation: 20,
  },
  modalScrollView: {
    flexGrow: 0,
    borderRadius: 32,
    overflow: 'hidden', // 애니메이션 동작 시 내부 콘텐츠 이탈 방지
  },
  modalScrollContent: {
    flexGrow: 1,
  },
  viewShotHighlight: {
    borderRadius: 32,
    overflow: 'hidden',
  },
  captureArea: {
    backgroundColor: '#fff',
    borderRadius: 32,
    padding: 24,
  },
  scoreCardHeader: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F5',
  },
  scoreCardTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0A2647',
    letterSpacing: 2,
  },
  scoreCardSubTitle: {
    fontSize: 13,
    color: '#6E85B7',
    fontWeight: '600',
    marginTop: 6,
  },
  tableGroup: {
    width: '100%',
    marginBottom: 16,
  },
  coursePartTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#495057',
    marginBottom: 10,
    marginLeft: 4,
  },
  legendContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    marginTop: 4,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#f8f9fa',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendLabel: {
    fontSize: 11,
    color: '#adb5bd',
    fontWeight: '600',
  },
  symbolCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#38E54D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  symbolCircleInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#38E54D',
  },
  symbolSquare: {
    width: 14,
    height: 14,
    borderWidth: 1,
    borderColor: '#FF6B6B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  symbolSquareInner: {
    width: 8,
    height: 8,
    borderWidth: 1,
    borderColor: '#FF6B6B',
  },
  symbolDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ADB5BD',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
    paddingHorizontal: 4,
  },
  shareBtn: {
    flex: 1,
    backgroundColor: '#007AFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 16,
    gap: 8,
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 5,
  },
  shareBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  closeBtn: {
    flex: 1,
    backgroundColor: '#F1F3F5',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeBtnText: {
    color: '#495057',
    fontSize: 15,
    fontWeight: '800',
  },
  promoContainer: {
    marginBottom: 20,
    marginHorizontal: 4,
    padding: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  promoSubText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 14,
    fontWeight: '600',
  },
});
