    -- 1. rounds 테이블 생성 (user_id 추가)
    CREATE TABLE IF NOT EXISTS public.rounds (
        id TEXT PRIMARY KEY,
        user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(), -- 사용자 ID (인성)
        date DATE NOT NULL,
        course_name TEXT NOT NULL,
        course_type TEXT,
        memo TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );

    -- 2. holes 테이블 생성 (round_id 외래키)
    CREATE TABLE IF NOT EXISTS public.holes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        round_id TEXT REFERENCES public.rounds(id) ON DELETE CASCADE NOT NULL,
        hole_no INTEGER NOT NULL,
        par INTEGER NOT NULL,
        stroke INTEGER NOT NULL,
        putt INTEGER NOT NULL,
        is_fairway BOOLEAN DEFAULT true,
        is_gir BOOLEAN,
        ob INTEGER DEFAULT 0,
        penalty INTEGER DEFAULT 0,
        miss_shot TEXT,
        
        UNIQUE(round_id, hole_no)
    );

    -- RLS (Row Level Security) 설정
    ALTER TABLE public.rounds ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.holes ENABLE ROW LEVEL SECURITY;

    -- 정책 재구성 (자신이 소유한 데이터에만 액세스 허용)
    DROP POLICY IF EXISTS "Allow user to manage their own rounds" ON public.rounds;
    CREATE POLICY "Allow user to manage their own rounds" 
    ON public.rounds FOR ALL 
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Allow user to manage their own holes" ON public.holes;
    CREATE POLICY "Allow user to manage their own holes" 
    ON public.holes FOR ALL 
    USING (
        EXISTS (
            SELECT 1 FROM public.rounds 
            WHERE public.rounds.id = public.holes.round_id 
            AND public.rounds.user_id = auth.uid()
        )
    );
