-- 1. rounds 테이블 생성
CREATE TABLE IF NOT EXISTS public.rounds (
    id TEXT PRIMARY KEY, -- round_Timestamp 형식 유지 또는 UUID
    date DATE NOT NULL,
    course_name TEXT NOT NULL,
    course_type TEXT,
    memo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. holes 테이블 생성 (round_id 외래키)
CREATE TABLE IF NOT EXISTS public.holes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id TEXT REFERENCES public.rounds(id) ON DELETE CASCADE NOT NULL,
    hole_no INTEGER NOT NULL,
    par INTEGER NOT NULL,
    stroke INTEGER NOT NULL,
    putt INTEGER NOT NULL,
    is_fairway BOOLEAN DEFAULT true,
    is_gir BOOLEAN,
    ob INTEGER DEFAULT 0,
    penalty INTEGER DEFAULT 0,
    miss_shot TEXT,
    
    UNIQUE(round_id, hole_no)
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holes ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제 (이미 존재할 경우 에러 방지용)
DROP POLICY IF EXISTS "Allow anonymous access to rounds" ON public.rounds;
DROP POLICY IF EXISTS "Allow anonymous access to holes" ON public.holes;

-- 신규 정책 생성
CREATE POLICY "Allow anonymous access to rounds" ON public.rounds FOR ALL USING (true);
CREATE POLICY "Allow anonymous access to holes" ON public.holes FOR ALL USING (true);
